# Generated by Django 3.0.4 on 2020-03-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='school',
            table='tbl_schools',
        ),
    ]
