# Generated by Django 3.0.4 on 2020-03-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='tbl_students',
        ),
    ]
