# Generated by Django 3.0.4 on 2020-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200324_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
