# Generated by Django 3.0.4 on 2020-03-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20200324_1635'),
        ('students', '0003_student_parent_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
